# Game Layers, not sure if it willl be used
LAYER_BACKGROUND = 0
LAYER_PLATFORMS = 1
LAYER_MAIN = 2
LAYER_FOREGROUND = 3

# Assets
SPRITESHEET_PATH = "data/"
LEVELS_PATH = "data/sprites/levels/"
PROPS_PATH = "data/environment/props/"
FONT_PATH = "data/Assets/Fonts/ENDOR___.ttf"
WINDOW_WIDTH = 960
WINDOW_HEIGHT = 540
FLYING_ENEMY_SPEED = 2
FLYING_ENEMY_ANIMATION_SPEED = 0.1
HERO_ANIMATION_SPEED_DEFFAULT = 0.25
HERO_ANIMATION_SPEED_IDLE = 0.1
HERO_ANIMATION_SPEED_RUN = 0.2
HERO_ANIMATION_SPEED_JUMP = 0.18
HERO_ANIMATION_SPEED_RUN_SHOOT = 0.2
HERO_ANIMATION_SPEED_DIE = 0.1
HERO_ANIMATION_SPEED_HURT = 0.1
HERO_SPEED = 4
TILESIZE = 16
HERO_GRAVITY = 0.4
HERO_JUMP_SPEED = -10
BULLET_SPEED = 7
BULLET_ANIMATION_SPEED = 0.25
HERO_FIRE_DELAY_MS = 180
SHOOT_ANIM_TIME_MS = 120
TURRET_ANIMATION_SPEED = 0.1
TURRET_ATTACK_ANIMATION_SPEED = 0.05
TURRET_DETECTION_RANGE = 200
TURRET_FIRE_DELAY_MS = 1500
